# Generated by Django 3.2.6 on 2021-12-15 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reporting.models.helpers.foriegn_key_code_based


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('current_price', models.TextField(null=True)),
                ('currency_id', models.TextField(null=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.TextField(null=True)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('username', models.TextField(db_index=True)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', reporting.models.helpers.foriegn_key_code_based.ForeignKeyCodeBased(db_column='role_code', on_delete=django.db.models.deletion.CASCADE, to='reporting.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='reporting.user')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='uq_username'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='reporting.user'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=reporting.models.helpers.foriegn_key_code_based.ForeignKeyCodeBased(db_column='permission_code', on_delete=django.db.models.deletion.CASCADE, to='reporting.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=reporting.models.helpers.foriegn_key_code_based.ForeignKeyCodeBased(db_column='role_code', on_delete=django.db.models.deletion.CASCADE, to='reporting.role'),
        ),
    ]
