apiVersion: v1
kind: Namespace
metadata:
   name: sda-portal

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: sda-portal
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          # volumeMounts:
          #   - name: postgresql-db-disk
          #     mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: portal
            # - name: PGDATA
            #   value: /data/pgdata
  # # Volume Claim
  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgresql-db-disk
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 25Gi

---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
  namespace: sda-portal
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432